# obtained from OpenShift
openshift_login: <oc_login_command>
# user's upspin email
upspin_email: <upspin_email>
# this is template.yaml for this project
yaml_file: template.yaml
# line 35 in template.yaml
template_name: <template_name>
# user defined cname
cname: <cname> 
# bearer token is user specific and secret
bearer_token: <bearer_token> 
# line 213 of template.yaml
route_name: <route_name> 
# line 221 of template.yaml
openshift_host_name: <openshift_host_name> 
